### ISSUE TITLE
main.py and jdk8 error

### ISSUE THREAD

**Issue by Centurion83** [PACROM/android#1]
rror: Cannot checkout platform/prebuilts/jdk/jdk8: GitError: platform/prebuilts/jdk/jdk8 rev-list ('^b0ea824a790f9445cc2f1ae1d78402214450fa50', 'HEAD', '--'): fatal: not a git repository (or any of the parent directories): .git

Traceback (most recent call last):
  File "/home/centurion/pacman/.repo/repo/main.py", line 572, in <module>
    _Main(sys.argv[1:])
  File "/home/centurion/pacman/.repo/repo/main.py", line 547, in _Main
    result = run()
  File "/home/centurion/pacman/.repo/repo/main.py", line 540, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/centurion/pacman/.repo/repo/main.py", line 201, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/centurion/pacman/.repo/repo/subcmds/sync.py", line 993, in Execute
    self._Checkout(all_projects, opt)
  File "/home/centurion/pacman/.repo/repo/subcmds/sync.py", line 554, in _Checkout
    self._CheckoutWorker(**kwargs)
  File "/home/centurion/pacman/.repo/repo/subcmds/sync.py", line 439, in _Checko

Just letting you know of the error for others. I will correct this on my local. Cool to see PacMan again. Cheers

**Comment by PACROM** [comment]
Sorry kinda got started but wanted to wait for android 10 before I released it on xda publicly. Working on the branches now to get everything started.

**Comment by Centurion83** [comment]
Oh cool. I added the jdks and it all fixed. Let me know if youd like me to
push em to help ya out. Cheers

**Comment by PACROM** [comment]
actually thats a great idea! let me...just give me a couple mins while I finish up supper with the kiddies and ill be back shortly once they go down for the rest of the evening. I've been messing around with dm-verity today and the new marlin kernel

**Comment by PACROM** [comment]
you have any experience with vendor blobs by any chance?

**Comment by Centurion83** [comment]
Manifest in platform/prebuilts/jdk/jdk8 was empty, sounds good, I have kids to pick up myself, I have test bench devices for Marlin, Sarge, Bonito and Crosshatch as well. Happy to throw some trees together and help with OTAs or whatever. Coming into slow work season. Might as well do something to kill time

**Comment by Centurion83** [comment]
I do, ill be back in about an hour from grabbing kids and such I can link with you @ ericharper27@gmail.com

**Comment by Centurion83** [comment]
mka
